### ISSUE TITLE
v4 update todos: extend Component, > React v14 support, better trackmouse support

### ISSUE THREAD

**Issue by hartzis** [dogfessional/react-swipeable#66]
next update checklist/wishlist:

- [x] use `extend React.Component` - PR already in #64 
- [x] update peer `react` dep to `"react": "^0.14.0 || ^15.0.0-0 || ^16.0.0-0"`
- [x] add `prop-types` as dep
- [x] add improved `trackMouse` support via [#57/TanaseHagi](https://github.com/dogfessional/react-swipeable/issues/57#issuecomment-262467825), PR in #67
- [x] possibly change `preventDefaultTouchmoveEvent` to default to `false`, #69

**Comment by hartzis** [comment]
just a friendly update, I'm hoping to have the next version out sometime the week of May 1st :)

**Comment by hartzis** [comment]
this should all go out this week, May 1-5, as major version update v4

**Comment by hartzis** [comment]
just published v4 :)
